services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asset_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: sh -c "npx prisma generate && npx prisma migrate deploy && tsx watch src/server.ts"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/asset_management?schema=public
      PORT: 4000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:5173
      JWT_SECRET: this-is-a-secure-jwt-secret-for-development-purposes-only-32-chars-minimum
      ENCRYPTION_KEY: CbTnQfOPzNH4r+7usjdTnn/Z20qxUayUQrsWRCYjq8I=
      CALLMEBOT_API_KEY: "1044769"
      CALLMEBOT_SENDER_PHONE: "+905398240525"
      EMAIL_SENDER_ADDRESS: marketing.innogy@gmail.com
      EMAIL_SENDER_NAME: "AHMET ELHALİT İŞ TAKİBİ"
      EMAIL_APP_PASSWORD: ejlcadhxdaycufzi
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/node_modules

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/node_modules

volumes:
  pgdata:
